apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cdi
  namespace: argocd
spec:
  generators:
  # Only select external clusters, excludes local cluster
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "{{nameNormalized}}-cdi1"
    spec:
      project: default
      source:
        repoURL: https://github.com/Kalyan-0710/gitops-demo-acm.git
        targetRevision: HEAD
        path: applicationsets/cdi/manifests
      destination:
        server: "{{server}}"
        namespace: cdi
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
