apiVersion: build.openshift.io/v1
kind: BuildRequest
metadata:
  name: qod-api-br
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/dpkshetty/qod-api'
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      buildConfigName: qod-api
