kind: Build
apiVersion: build.openshift.io/v1
metadata:
  name: qod-api
  ownerReferences:
    - apiVersion: build.openshift.io/v1
      kind: BuildConfig
      name: qod-api
  labels:
    app: qod-api
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'qod-api:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/dpkshetty/qod-api'
    contextDir: /
