kind: Pod
apiVersion: v1
metadata:
  name: qod-api-build
  labels:
    openshift.io/build.name: qod-api
spec:
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  activeDeadlineSeconds: 604800
  initContainers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: git-clone
      env:
        - name: BUILD
          value: |
            {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"qod-api-1","namespace":"three-tier","uid":"20a9422b-e87d-4078-bb1b-b2f34e424382","resourceVersion":"1655855","generation":1,"creationTimestamp":"2024-10-20T15:50:24Z","labels":{"app":"qod-api","app.kubernetes.io/component":"qod-api","app.kubernetes.io/instance":"qod-api","app.kubernetes.io/name":"qod-api","app.kubernetes.io/part-of":"QOD","buildconfig":"qod-api","openshift.io/build-config.name":"qod-api","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"qod-api","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"qod-api","uid":"838af7bc-8a5a-4d72-87d2-641ee910a352","controller":true}],"managedFields":[{"manager":"openshift-apiserver","operation":"Update","apiVersion":"build.openshift.io/v1","time":"2024-10-20T15:50:24Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:openshift.io/build-config.name":{},"f:openshift.io/build.number":{}},"f:labels":{".":{},"f:app":{},"f:app.kubernetes.io/component":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/part-of":{},"f:buildconfig":{},"f:openshift.io/build-config.name":{},"f:openshift.io/build.start-policy":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"838af7bc-8a5a-4d72-87d2-641ee910a352\"}":{}}},"f:spec":{"f:output":{"f:to":{}},"f:serviceAccount":{},"f:source":{"f:contextDir":{},"f:git":{".":{},"f:uri":{}},"f:type":{}},"f:strategy":{"f:dockerStrategy":{".":{},"f:dockerfilePath":{}},"f:type":{}},"f:triggeredBy":{}},"f:status":{"f:conditions":{".":{},"k:{\"type\":\"New\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:status":{},"f:type":{}}},"f:config":{},"f:phase":{}}}}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/dpkshetty/qod-api"},"contextDir":"/"},"strategy":{"type":"Docker","dockerStrategy":{"pullSecret":{"name":"builder-dockercfg-wnrlj"},"dockerfilePath":"Dockerfile"}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/three-tier/qod-api:latest"},"pushSecret":{"name":"builder-dockercfg-wnrlj"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Build configuration change"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/three-tier/qod-api:latest","config":{"kind":"BuildConfig","namespace":"three-tier","name":"qod-api"},"output":{},"conditions":[{"type":"New","status":"True","lastUpdateTime":"2024-10-20T15:50:24Z","lastTransitionTime":"2024-10-20T15:50:24Z"}]}}
        - name: LANG
          value: C.utf8
        - name: SOURCE_REPOSITORY
          value: 'https://github.com/dpkshetty/qod-api'
        - name: SOURCE_URI
          value: 'https://github.com/dpkshetty/qod-api'
        - name: SOURCE_CONTEXT_DIR
          value: /
        - name: BUILD_REGISTRIES_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/registries.conf
        - name: BUILD_REGISTRIES_DIR_PATH
          value: /var/run/configs/openshift.io/build-system/registries.d
        - name: BUILD_SIGNATURE_POLICY_PATH
          value: /var/run/configs/openshift.io/build-system/policy.json
        - name: BUILD_STORAGE_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/storage.conf
        - name: BUILD_BLOBCACHE_DIR
          value: /var/cache/blobs
        - name: HTTP_PROXY
        - name: http_proxy
        - name: HTTPS_PROXY
        - name: https_proxy
        - name: NO_PROXY
        - name: no_proxy
      securityContext:
        capabilities:
          add:
            - CHOWN
            - DAC_OVERRIDE
          drop:
            - ALL
        privileged: false
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: buildworkdir
          mountPath: /tmp/build
        - name: build-system-configs
          readOnly: true
          mountPath: /var/run/configs/openshift.io/build-system
        - name: build-ca-bundles
          mountPath: /var/run/configs/openshift.io/certs
        - name: build-proxy-ca-bundles
          mountPath: /var/run/configs/openshift.io/pki
        - name: build-blob-cache
          mountPath: /var/cache/blobs
        - name: kube-api-access-tc4tb
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: FallbackToLogsOnError
      image: 'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:78821c20ffb87d62624c9a0e1851f9182fe93d135b8a277dba7a38132155d199'
      args:
        - openshift-git-clone
        - '--v=0'
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: manage-dockerfile
      env:
        - name: BUILD
          value: |
            {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"qod-api-1","namespace":"three-tier","uid":"20a9422b-e87d-4078-bb1b-b2f34e424382","resourceVersion":"1655855","generation":1,"creationTimestamp":"2024-10-20T15:50:24Z","labels":{"app":"qod-api","app.kubernetes.io/component":"qod-api","app.kubernetes.io/instance":"qod-api","app.kubernetes.io/name":"qod-api","app.kubernetes.io/part-of":"QOD","buildconfig":"qod-api","openshift.io/build-config.name":"qod-api","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"qod-api","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"qod-api","uid":"838af7bc-8a5a-4d72-87d2-641ee910a352","controller":true}],"managedFields":[{"manager":"openshift-apiserver","operation":"Update","apiVersion":"build.openshift.io/v1","time":"2024-10-20T15:50:24Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:openshift.io/build-config.name":{},"f:openshift.io/build.number":{}},"f:labels":{".":{},"f:app":{},"f:app.kubernetes.io/component":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/part-of":{},"f:buildconfig":{},"f:openshift.io/build-config.name":{},"f:openshift.io/build.start-policy":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"838af7bc-8a5a-4d72-87d2-641ee910a352\"}":{}}},"f:spec":{"f:output":{"f:to":{}},"f:serviceAccount":{},"f:source":{"f:contextDir":{},"f:git":{".":{},"f:uri":{}},"f:type":{}},"f:strategy":{"f:dockerStrategy":{".":{},"f:dockerfilePath":{}},"f:type":{}},"f:triggeredBy":{}},"f:status":{"f:conditions":{".":{},"k:{\"type\":\"New\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:status":{},"f:type":{}}},"f:config":{},"f:phase":{}}}}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/dpkshetty/qod-api"},"contextDir":"/"},"strategy":{"type":"Docker","dockerStrategy":{"pullSecret":{"name":"builder-dockercfg-wnrlj"},"dockerfilePath":"Dockerfile"}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/three-tier/qod-api:latest"},"pushSecret":{"name":"builder-dockercfg-wnrlj"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Build configuration change"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/three-tier/qod-api:latest","config":{"kind":"BuildConfig","namespace":"three-tier","name":"qod-api"},"output":{},"conditions":[{"type":"New","status":"True","lastUpdateTime":"2024-10-20T15:50:24Z","lastTransitionTime":"2024-10-20T15:50:24Z"}]}}
        - name: LANG
          value: C.utf8
        - name: SOURCE_REPOSITORY
          value: 'https://github.com/dpkshetty/qod-api'
        - name: SOURCE_URI
          value: 'https://github.com/dpkshetty/qod-api'
        - name: SOURCE_CONTEXT_DIR
          value: /
        - name: BUILD_REGISTRIES_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/registries.conf
        - name: BUILD_REGISTRIES_DIR_PATH
          value: /var/run/configs/openshift.io/build-system/registries.d
        - name: BUILD_SIGNATURE_POLICY_PATH
          value: /var/run/configs/openshift.io/build-system/policy.json
        - name: BUILD_STORAGE_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/storage.conf
        - name: BUILD_BLOBCACHE_DIR
          value: /var/cache/blobs
        - name: HTTP_PROXY
        - name: http_proxy
        - name: HTTPS_PROXY
        - name: https_proxy
        - name: NO_PROXY
        - name: no_proxy
      securityContext:
        capabilities:
          add:
            - CHOWN
            - DAC_OVERRIDE
          drop:
            - ALL
        privileged: false
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: buildworkdir
          mountPath: /tmp/build
        - name: build-system-configs
          readOnly: true
          mountPath: /var/run/configs/openshift.io/build-system
        - name: build-ca-bundles
          mountPath: /var/run/configs/openshift.io/certs
        - name: build-proxy-ca-bundles
          mountPath: /var/run/configs/openshift.io/pki
        - name: build-blob-cache
          mountPath: /var/cache/blobs
        - name: kube-api-access-tc4tb
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: FallbackToLogsOnError
      image: 'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:78821c20ffb87d62624c9a0e1851f9182fe93d135b8a277dba7a38132155d199'
      args:
        - openshift-manage-dockerfile
        - '--v=0'
  serviceAccountName: builder
  imagePullSecrets:
    - name: builder-dockercfg-wnrlj
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: ip-10-0-1-126.us-east-2.compute.internal
  securityContext: {}
  containers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: docker-build
      env:
        - name: BUILD
          value: |
            {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"qod-api-1","namespace":"three-tier","uid":"20a9422b-e87d-4078-bb1b-b2f34e424382","resourceVersion":"1655855","generation":1,"creationTimestamp":"2024-10-20T15:50:24Z","labels":{"app":"qod-api","app.kubernetes.io/component":"qod-api","app.kubernetes.io/instance":"qod-api","app.kubernetes.io/name":"qod-api","app.kubernetes.io/part-of":"QOD","buildconfig":"qod-api","openshift.io/build-config.name":"qod-api","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"qod-api","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"qod-api","uid":"838af7bc-8a5a-4d72-87d2-641ee910a352","controller":true}],"managedFields":[{"manager":"openshift-apiserver","operation":"Update","apiVersion":"build.openshift.io/v1","time":"2024-10-20T15:50:24Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:openshift.io/build-config.name":{},"f:openshift.io/build.number":{}},"f:labels":{".":{},"f:app":{},"f:app.kubernetes.io/component":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/part-of":{},"f:buildconfig":{},"f:openshift.io/build-config.name":{},"f:openshift.io/build.start-policy":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"838af7bc-8a5a-4d72-87d2-641ee910a352\"}":{}}},"f:spec":{"f:output":{"f:to":{}},"f:serviceAccount":{},"f:source":{"f:contextDir":{},"f:git":{".":{},"f:uri":{}},"f:type":{}},"f:strategy":{"f:dockerStrategy":{".":{},"f:dockerfilePath":{}},"f:type":{}},"f:triggeredBy":{}},"f:status":{"f:conditions":{".":{},"k:{\"type\":\"New\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:status":{},"f:type":{}}},"f:config":{},"f:phase":{}}}}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/dpkshetty/qod-api"},"contextDir":"/"},"strategy":{"type":"Docker","dockerStrategy":{"pullSecret":{"name":"builder-dockercfg-wnrlj"},"dockerfilePath":"Dockerfile"}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/three-tier/qod-api:latest"},"pushSecret":{"name":"builder-dockercfg-wnrlj"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Build configuration change"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/three-tier/qod-api:latest","config":{"kind":"BuildConfig","namespace":"three-tier","name":"qod-api"},"output":{},"conditions":[{"type":"New","status":"True","lastUpdateTime":"2024-10-20T15:50:24Z","lastTransitionTime":"2024-10-20T15:50:24Z"}]}}
        - name: LANG
          value: C.utf8
        - name: SOURCE_REPOSITORY
          value: 'https://github.com/dpkshetty/qod-api'
        - name: SOURCE_URI
          value: 'https://github.com/dpkshetty/qod-api'
        - name: SOURCE_CONTEXT_DIR
          value: /
        - name: PUSH_DOCKERCFG_PATH
          value: /var/run/secrets/openshift.io/push
        - name: PULL_DOCKERCFG_PATH
          value: /var/run/secrets/openshift.io/pull
        - name: BUILD_REGISTRIES_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/registries.conf
        - name: BUILD_REGISTRIES_DIR_PATH
          value: /var/run/configs/openshift.io/build-system/registries.d
        - name: BUILD_SIGNATURE_POLICY_PATH
          value: /var/run/configs/openshift.io/build-system/policy.json
        - name: BUILD_STORAGE_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/storage.conf
        - name: BUILD_BLOBCACHE_DIR
          value: /var/cache/blobs
        - name: HTTP_PROXY
        - name: http_proxy
        - name: HTTPS_PROXY
        - name: https_proxy
        - name: NO_PROXY
        - name: no_proxy
      securityContext:
        privileged: true
        runAsUser: 0
        runAsGroup: 0
        seccompProfile:
          type: Unconfined
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: node-pullsecrets
          mountPath: /var/lib/kubelet/config.json
        - name: buildworkdir
          mountPath: /tmp/build
        - name: buildcachedir
          mountPath: /var/lib/containers/cache
        - name: builder-dockercfg-wnrlj-push
          readOnly: true
          mountPath: /var/run/secrets/openshift.io/push
        - name: builder-dockercfg-wnrlj-pull
          readOnly: true
          mountPath: /var/run/secrets/openshift.io/pull
        - name: build-system-configs
          readOnly: true
          mountPath: /var/run/configs/openshift.io/build-system
        - name: build-ca-bundles
          mountPath: /var/run/configs/openshift.io/certs
        - name: build-proxy-ca-bundles
          mountPath: /var/run/configs/openshift.io/pki
        - name: container-storage-root
          mountPath: /var/lib/containers
        - name: container-storage-run
          mountPath: /var/run/containers
        - name: build-blob-cache
          mountPath: /var/cache/blobs
        - name: kube-api-access-tc4tb
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: FallbackToLogsOnError
      image: 'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:78821c20ffb87d62624c9a0e1851f9182fe93d135b8a277dba7a38132155d199'
      args:
        - openshift-docker-build
        - '--v=0'
  serviceAccount: builder
  volumes:
    - name: buildcachedir
      hostPath:
        path: /var/lib/containers/cache
        type: ''
    - name: buildworkdir
      emptyDir: {}
    - name: node-pullsecrets
      hostPath:
        path: /var/lib/kubelet/config.json
        type: File
    - name: builder-dockercfg-wnrlj-push
      secret:
        secretName: builder-dockercfg-wnrlj
        defaultMode: 384
    - name: builder-dockercfg-wnrlj-pull
      secret:
        secretName: builder-dockercfg-wnrlj
        defaultMode: 384
    - name: build-system-configs
      configMap:
        name: qod-api-1-sys-config
        defaultMode: 420
    - name: build-ca-bundles
      configMap:
        name: qod-api-1-ca
        items:
          - key: service-ca.crt
            path: 'certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt'
        defaultMode: 420
    - name: build-proxy-ca-bundles
      configMap:
        name: qod-api-1-global-ca
        items:
          - key: ca-bundle.crt
            path: tls-ca-bundle.pem
        defaultMode: 420
    - name: container-storage-root
      emptyDir: {}
    - name: container-storage-run
      emptyDir: {}
    - name: build-blob-cache
      emptyDir: {}
    - name: kube-api-access-tc4tb
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
