apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm1
  labels:
    app: httpd
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: demo-vm1-ds-fedora
    spec:
      sourceRef:
        kind: DataSource
        name: fedora-httpd
        namespace: demo-vm3
      storage:
        resources: {}
  template:
    metadata:
      labels:
        special: httpd
    spec:
      terminationGracePeriodSeconds: 180
      domain:
        devices:
          rng: {}
        memory:
          guest: 1024M
      volumes:
      - dataVolume:
          name: demo-vm1-ds-fedora
        name: demo-vm1-ds-fedora
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
