apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm3
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: demo-vm3-ds-fedora
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources: {}
  template:
    metadata:
      labels:
        expose: demo-vm3
    spec:
      hostname: demo-vm3
      subdomain: demo-vm
      terminationGracePeriodSeconds: 180
      domain:
        devices:
          rng: {}
        memory:
          guest: 1024M
      volumes:
      - dataVolume:
          name: demo-vm3-ds-fedora
        name: demo-vm3-ds-fedora
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
