apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm1
  labels:
    app: httpd
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: demo-vm1-ds-fedora
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources: {}
  - template:
    - metadata:
        label:
          app: httpd
    spec:
      terminationGracePeriodSeconds: 180
      domain:
        devices:
          rng: {}
        memory:
          guest: 1024M
      volumes:
      - dataVolume:
          name: demo-vm1-ds-fedora
        name: demo-vm1-ds-fedora
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
